version: '3.11'

networks:
  app_network:
    name: app_network

services:
  app_serving:
    image: nhl-service:latest
    build:
      context: .
      dockerfile: Dockerfile.serving
      args:
        - COMET_API_KEY=${COMET_KEY}
    ports:
      - "8080:8080"
    environment:
      COMET_API_KEY: ${COMET_KEY}
    networks:
      - app_network

  app_streamlit:
    image: nhl-streamlit:latest
    build:
      context: .
      dockerfile: Dockerfile.streamlit
      args:
        - COMET_API_KEY=${COMET_KEY}
    ports:
      - "8501:8501"
    environment:
      COMET_API_KEY: ${COMET_KEY}
    networks:
      - app_network
